require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '11.0'

target 'seek_o_mobile' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false
  )
  pod 'XCDYouTubeKit', '~> 2.8'
  pod 'Google', '<=1.3.2'
  pod 'GoogleUtilities', '<=1.1.0'
  pod 'RNPurchases', :path => '../node_modules/react-native-purchases', :inhibit_warnings => true, :modular_headers => false

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  target 'seek_o_mobileTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
  # use_flipper!()

#   post_install do |installer|
#     react_native_post_install(installer)
#     __apply_Xcode_12_5_M1_post_install_workaround(installer)
#   end
  
#  post_install do |installer|
#      installer.pods_project.targets.each do |target|
#        target.build_configurations.each do |config|
#          config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
#          config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
#        end
#      end
#    end
end
